\documentclass{article}

\usepackage[spanish]{babel}
\usepackage[utf8]{inputenc}
\usepackage[right=1.5cm,left=1.5cm,top=1.5cm,bottom=1.5cm]{geometry}

\title{Taller 3A\\ Estadística genómica}
\author{Juan David Henao Sánchez}

\begin{document}
\SweaveOpts{concordance=TRUE}

\maketitle

\section*{Sobre unos datos del GEO (una sola medición en el tiempo) que comparen dos condiciones, identifique los genes diferencialmente expresados usando acde:
}

<<>>=

library(acde)
library("DESeq")
#########################
data <- read.table("GSE58972_RELA_6h_processed_data.txt", h=T)
dim(data)
head(data)
@
<<fig=TRUE>>=
boxplot(data[, 3:8], main="Boxplot Mus musculus", col="lightgreen", cex.names=0.2, las=2)
@
<<>>=
rownames(data) <- data$gene
countsTable <- data[,3:8]
head(countsTable)
conds <- factor( c( "WT", "WT", "WT", "treated","treated","treated"))
cds <- newCountDataSet( countsTable, conds )
####################################################
cds <- estimateSizeFactors( cds )
sizeFactors(cds)
head(counts(cds,normalized=TRUE))
cds <- estimateDispersions( cds )
#####################################################
plotDispEsts <- function( cds ){
  
  plot(rowMeans( counts( cds, normalized=TRUE ) ), fitInfo(cds)
       
       $perGeneDispEsts, pch = '.', log="xy", ylab="dispersion",
       
       xlab="mean of normalized counts")
  
  xg = 10^seq( -.5, 5, length.out=300 )
  
  lines( xg, fitInfo(cds)$dispFun( xg ), col="red" )
  
}
@
<<fig=TRUE>>=

plotDispEsts(cds)
@
<<>>=
res = nbinomTest(cds,"WT","treated")
head(res)
@
<<fig=TRUE>>=
plotMA(res)
hist(res$pval, breaks=100, col="skyblue", border="slateblue", main="")
@
<<>>=
resSig = res[ res$padj < 0.1, ]
head(resSig)
@

\end{document}

