\documentclass{article}

\usepackage[spanish]{babel}
\usepackage[utf8]{inputenc}
\usepackage[right=1.5cm,left=1.5cm,top=1.5cm,bottom=1.5cm]{geometry}

\title{Taller 3A\\ Estadística genómica}
\author{Juan David Henao Sánchez}

\begin{document}
\SweaveOpts{concordance=TRUE}

\maketitle

\section*{Sobre unos datos del GEO (una sola medición en el tiempo) que comparen dos condiciones, identifique los genes diferencialmente expresados usando acde:
}

\begin{itemize}
\item{Cargando las librerias}
<<>>=
library(acde)
library("DESeq")
@
\item{Cargando los datos}
<<>>=
data <- read.table("GSE58972_RELA_6h_processed_data.txt", h=T)
dim(data)
head(data)
@
\item{Gráficando los datos cargados}
<<fig=TRUE>>=
boxplot(data[, 3:8], main="Boxplot Mus musculus", col="lightgreen", cex.names=0.2, las=2)
@
\item{Creando el CountDataSet}
<<>>=
rownames(data) <- data$gene
countsTable <- data[,3:8]
head(countsTable)
conds <- factor( c( "WT", "WT", "WT", "treated","treated","treated"))
cds <- newCountDataSet( countsTable, conds )
@
\item{Estimando el tamaño de los datos}
<<>>=
cds <- estimateSizeFactors( cds )
sizeFactors(cds)
@
\item{Normalización}
<<>>=
head(counts(cds,normalized=TRUE))
@
\item{Estimando las diferencias}
<<>>=
cds <- estimateDispersions( cds )
res = nbinomTest(cds,"WT","treated")
head(res)
@
\item{Gráficando los resultados obtenidos}
<<fig=TRUE>>=
plotMA(res)
@
\item{Resultados finales}
<<>>=
resSig = res[ res$padj < 0.1, ]
na.omit(dim(resSig))
na.omit(head(resSig))
@
\end{itemize}
\end{document}

